### ISSUE TITLE
Not compatible with Python 3.6

### ISSUE THREAD

**Issue by Givralix** [niner/inline-python-pm#19]
After updating Python to 3.6, my script fails with this error:
> An eval() failed in Inline::glue:
> Can't load '/usr/lib/perl5/site_perl/auto/Inline/Python/Python.so' for module Inline::Python: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory at /usr/lib/perl5/core_perk/DynaLoader.pm line 193.
>  at perlbot.pl line 11.
> Compilation failed in require at (eval 209) line 2.
> 
> 
>  at perlbot.pl line 11.
> BEGIN failed--compilation aborted at perlbot.pl line 11.

Downgrading back to Python 3.5 works perfectly, however.

**Comment by niner** [comment]
It tries to load a libpython3.5m.so.1.0, i.e. the Python 3.5 library.

Looks to me like you've installed Inline::Python, and then afterwards upgraded your Python to 3.6? In that case you'd have to re-install Inline::Python, so it links against the newer Python library. Can you confirm?
